apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kong.dblessConfig.configMap }}
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    services:
     
      # keycloak example
      - host: "orion-ld-two"
        name: "orion-ld"
        port: 1026
        protocol: http

        routes:
          - name: orion-ld
            paths:
              - /orion-ld
            strip_path: true

        plugins:
          - name: prometheus

          - name: rate-limiting
            config: 
              minute: 30
