trusted-issuers-list:
  route: 
    til: 
      enabled: true 
      host: trusted-issuers-config.batterypass.fiware.dev
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      certificate:
        issuer:
          kind: ClusterIssuer
          name: letsencrypt-aws-prod
    tir: 
      enabled: true 
      host: trusted-issuers.batterypass.fiware.dev
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      certificate:
        issuer:
          kind: ClusterIssuer
          name: letsencrypt-aws-prod
  
  deployment:
    image:  
      tag: 0.0.3
  database:
    persistence: true
    host: mysql-bp
    username: root
    name: til
    existingSecret:
      enabled: true
      name: mysql-secret
      key: dbPassword