apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kong.dblessConfig.configMap }}
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    consumers:
    - username: token-consumer
      keyauth_credentials:
      - tags: 
        - token-key

    services:
      
      - host: "token-helper"
        name: "token-helper"
        port: 8080
        protocol: http

        routes:
          - name: token-helper
            paths:
              - /token
            strip_path: true

        plugins:
          - name: prometheus

          - name: key-auth
            config: 
              hide_credentials: true 
              key_in_header: true 
              key_names:
                - API_KEY
               
          - name: rate-limiting
            config: 
              minute: 30

      - host: "orion-ld-one"
        name: "orion-ld"
        port: 1026
        protocol: http

        routes:
          - name: orion-ld
            paths:
              - /orion-ld
            strip_path: true

        plugins:
          - name: prometheus

          - name: rate-limiting
            config: 
              minute: 30