route:
  enabled: true
  host: one.batterypass.fiware.dev
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  certificate:
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-aws-prod

vcwaltid:
  deployment:
    image:  
      repository: quay.io/fiware/waltid
      tag: 1.14.0-SNAPSHOT
      pullPolicy: Always
  api:
    core: 
      enabled: true
    auditor: 
      enabled: true
    signatory: 
      enabled: true
    custodian: 
      enabled: true
    essif: 
      enabled: true

  persistence: 
    enabled: false
    pvc:
      size: 1Gi

  templates:
    GaiaXParticipantCredential.json: |
      {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
        ],
        "type": [
          "VerifiableCredential"
        ],
        "id": "did:web:raw.githubusercontent.com:egavard:payload-sign:master",
        "issuer": "did:web:raw.githubusercontent.com:egavard:payload-sign:master",
        "issuanceDate": "2023-03-21T12:00:00.148Z",
        "credentialSubject": {
          "id": "did:web:raw.githubusercontent.com:egavard:payload-sign:master",
          "type": "gx:LegalParticipant",
          "gx:legalName": "Gaia-X compliant participant",
          "gx:legalRegistrationNumber": {
            "gx:vatID": "MYVATID"
          },
          "gx:headquarterAddress": {
            "gx:countrySubdivisionCode": "BE-BRU"
          },
          "gx:legalAddress": {
            "gx:countrySubdivisionCode": "BE-BRU"
          },
          "gx-terms-and-conditions:gaiaxTermsAndConditions": "70c1d713215f95191a11d38fe2341faed27d19e083917bc8732ca4fea4976700"
        }
      }
    BatteryPassAuthCredential.json: |
      {
        "@context": ["https://www.w3.org/2018/credentials/v1"],
        "credentialSchema": {
          "id": "https://raw.githubusercontent.com/FIWARE-Ops/batterypass-demonstrator/main/docs/schema.json",
          "type": "FullJsonSchemaValidator2021"
        },
        "credentialSubject": {
          "familyName": "Happy",
          "firstName": "User",
          "roles": [{
            "names": ["P.Info.gold"],
            "target": "did:elsi:target"
          }]
        },
        "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
        "issued": "2021-08-31T00:00:00Z",
        "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
        "validFrom": "2021-08-31T00:00:00Z",
        "issuanceDate": "2021-08-31T00:00:00Z",
        "type": ["VerifiableCredential", "BatteryPassAuthCredential"]
      }