mysql:
  fullnameOverride: mysql-bp
  auth:
    existingSecret: mysql-secret
  rbac: 
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use