apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "waltid.fullname" . }}-certs
  labels:
    {{ include "waltid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
  {{- with .Values.deployment.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "waltid.name" . }}-certs
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "waltid.labels" . | nindent 8 }}
        {{- with .Values.deployment.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.deployment.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec: 
      serviceAccountName: {{ include "waltid.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: Always
          image: "lipanski/docker-static-website:2.1.0"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: certs
              mountPath: /home/static/certs
      volumes:
        - name: certs
          configMap:
            name: {{ include "waltid.fullname" . }}
            secret:
              secretName: {{ include "waltid.fullname" . }}-tls-sec
              items: 
                - key: tls.crt