apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-key
data:
  keyfile.json: |-
    { 
      "kty": "OKP",
      "d": "mZ2cSbz2Df8PDw1T9k8GV3k-f8eCWmaqIRYBj4R9hgE",
      "use": "sig",
      "crv": "Ed25519",
      "kid": "z6MkpSdSEX5EB31EqW8RqvVpwbgUVyTW88H6s9QXhsLZXvSr",
      "x": "lGt5gmNyElQ9ST4OypKGDk25LnnK4pRZdNHnOVoxHF8",
      "alg": "EdDSA"
    }