vcverifier:
  deployment:
    image:
      repository: quay.io/fiware/vcverifier
      tag: 1.1.2-pre-7
      pullPolicy: Always
    logging: 
      level: DEBUG
      pathsToSkip: 
        - "/health"
    ssikit:
      auditorUrl: http://waltid-one-vcwaltid:7003
    verifier:
      tirAddress: https://satellite.batterypass.fiware.dev/trusted_issuer/v3/issuers
      did: did:key:z6MkigCEnopwujz8Ten2dzq91nvMjqbKQYcifuZhqBsEkH7g
   
  route:
    enabled: true
    host: verifier-one.batterypass.fiware.dev
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    certificate:
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-aws-prod
  
