vcverifier:
  deployment:
    protectedResource: https://one.batterypass.fiware.dev/vc/ngsi-ld/v1/entities?type=DELIVERYORDER
    walt:
      coreUrl: http://waltid-one-vcwaltid:7000
      signatoryUrl: http://waltid-one-vcwaltid:7001
      auditorUrl: http://waltid-one-vcwaltid:7002
      custodianUrl: http://waltid-one-vcwaltid:7003
      essifUrl: http://waltid-one-vcwaltid:7010
  route:
    enabled: true
    host: verifier-one.batterypass.fiware.dev
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    certificate:
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-aws-prod
  
