## values to be used for deployement in demo namespace
## additional config file is used, since we rely on managed databases there.

source: https://github.com/fiware-ops/batterypass
release: batterypass
destination_namespace: &destination batterypass
branch: &branch main
secretsEnabled: &secretsEnabled false

applications:
  - name: mongodb-one
    enabled: true
    source_path: applications/mongodb-one
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: mongodb-two
    enabled: true
    source_path: applications/mongodb-two
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: mongodb-three
    enabled: true
    source_path: applications/mongodb-three
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml 

  - name: orion-ld-one
    enabled: true
    source_path: applications/orion-ld-one
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: orion-ld-two
    enabled: true
    source_path: applications/orion-ld-two
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: orion-ld-three
    enabled: true
    source_path: applications/orion-ld-three
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml 

  - name: kong-one
    enabled: true
    source_path: applications/kong-one
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: kong-two
    enabled: true
    source_path: applications/kong-two
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml 

  - name: kong-three
    enabled: true
    source_path: applications/kong-three
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml