## values to be used for deployement in demo namespace
## additional config file is used, since we rely on managed databases there.

source: https://github.com/fiware-ops/batterypass-demonstrator
release: batterypass
destination_namespace: &destination batterypass
purpose: &purpose batterypass-demo-env
branch: &branch main
secretsEnabled: &secretsEnabled false

applications:
  - name: mongodb-one
    enabled: true
    source_path: applications/one/mongodb-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: mongodb-two
    enabled: true
    source_path: applications/two/mongodb-two
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: mongodb-three
    enabled: true
    source_path: applications/three/mongodb-three
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml 

  - name: orion-ld-one
    enabled: true
    source_path: applications/one/orion-ld-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: orion-ld-two
    enabled: true
    source_path: applications/two/orion-ld-two
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: orion-ld-three
    enabled: true
    source_path: applications/three/orion-ld-three
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml 

  - name: kong-one
    enabled: true
    source_path: applications/one/kong-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
    values: 
      kong:
        proxy: 
          route:
            host: one.batterypass.fiware.dev
            certificate:
              issuer:
                kind: ClusterIssuer
                name: letsencrypt-aws-prod

  - name: kong-two
    enabled: true
    source_path: applications/two/kong-two
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
    values: 
      kong:
        proxy: 
          route:
            host: two.batterypass.fiware.dev
            certificate:
              issuer:
                kind: ClusterIssuer
                name: letsencrypt-aws-prod

  - name: kong-three
    enabled: true
    source_path: applications/three/kong-three
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml 
    values: 
      kong:
        proxy: 
          route:
            host: three.batterypass.fiware.dev
            certificate:
              issuer:
                kind: ClusterIssuer
                name: letsencrypt-aws-prod
  
  - name: context-server
    enabled: true
    source_path: applications/context-server
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml 
    values: 
      route:
        host: context.batterypass.fiware.dev
        certificate:
          issuer:
            kind: ClusterIssuer
            name: letsencrypt-aws-prod

  - name: satellite
    enabled: true
    source_path: applications/satellite
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
    values:
      ishare-satellite:
        route:
          enabled: true
          host: satellite.batterypass.fiware.dev
          tls:
            termination: edge
            insecureEdgeTerminationPolicy: Redirect
          # should a certificate for the address automatically be generated
          certificate:
            issuer:
              kind: ClusterIssuer
              name: letsencrypt-aws-prod

  - name: mysql
    enabled: true
    source_path: applications/mysql
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: keyrock-one
    enabled: true
    source_path: applications/one/keyrock-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: keyrock-two
    enabled: true
    source_path: applications/two/keyrock-two
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: keyrock-three
    enabled: true
    source_path: applications/three/keyrock-three
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: token-helper
    enabled: true
    source_path: applications/token-helper
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: postgresql
    enabled: true
    source_path: applications/postgresql
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: keycloak-one
    enabled: true
    source_path: applications/one/keycloak-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: keycloak-two
    enabled: true
    source_path: applications/two/keycloak-two
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: keycloak-three
    enabled: true
    source_path: applications/three/keycloak-three
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: waltid-one
    enabled: true
    source_path: applications/one/waltid-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
    
  - name: waltid-two
    enabled: true
    source_path: applications/two/waltid-two
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: waltid-three
    enabled: true
    source_path: applications/three/waltid-three
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: verifier-one
    enabled: true
    source_path: applications/one/verifier-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: pdp-one
    enabled: true
    source_path: applications/one/pdp-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: portal-one
    enabled: true
    source_path: applications/one/portal-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: mysql-til
    enabled: true
    source_path: applications/mysql-til
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml


  - name: trusted-issuers
    enabled: true
    source_path: applications/trusted-issuers
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml




