## values to be used for deployement in demo namespace
## additional config file is used, since we rely on managed databases there.

source: https://github.com/fiware-ops/batterypass-demonstrator
release: batterypass
destination_namespace: &destination batterypass
purpose: &purpose batterypass-demo-env
branch: &branch main
secretsEnabled: &secretsEnabled false

applications:
  - name: mongodb-one
    enabled: true
    source_path: applications/mongodb-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: mongodb-two
    enabled: true
    source_path: applications/mongodb-two
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: mongodb-three
    enabled: true
    source_path: applications/mongodb-three
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml 

  - name: orion-ld-one
    enabled: true
    source_path: applications/orion-ld-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: orion-ld-two
    enabled: true
    source_path: applications/orion-ld-two
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: orion-ld-three
    enabled: true
    source_path: applications/orion-ld-three
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml 

  - name: kong-one
    enabled: true
    source_path: applications/kong-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
    values: 
      kong:
        proxy: 
          route:
            host: one.batterypass.fiware.dev
            certificate:
              issuer:
                kind: ClusterIssuer
                name: letsencrypt-aws-prod

  - name: kong-two
    enabled: true
    source_path: applications/kong-two
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
    values: 
      kong:
        proxy: 
          route:
            host: two.batterypass.fiware.dev
            certificate:
              issuer:
                kind: ClusterIssuer
                name: letsencrypt-aws-prod

  - name: kong-three
    enabled: true
    source_path: applications/kong-three
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml 
    values: 
      kong:
        proxy: 
          route:
            host: three.batterypass.fiware.dev
            certificate:
              issuer:
                kind: ClusterIssuer
                name: letsencrypt-aws-prod
  
  - name: context-server
    enabled: true
    source_path: applications/context-server
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml 
    values: 
      route:
        host: context.batterypass.fiware.dev
        certificate:
          issuer:
            kind: ClusterIssuer
            name: letsencrypt-aws-prod

  - name: satellite
    enabled: true
    source_path: applications/satellite
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
    values:
      ishare-satellite:
        route:
          enabled: true
          host: satellite.batterypass.fiware.dev
          tls:
            termination: edge
            insecureEdgeTerminationPolicy: Redirect
          # should a certificate for the address automatically be generated
          certificate:
            issuer:
              kind: ClusterIssuer
              name: letsencrypt-aws-prod

  - name: mysql
    enabled: true
    source_path: applications/mysql
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: ar
    enabled: true
    source_path: applications/keyrock-ar
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: keyrock-one
    enabled: true
    source_path: applications/keyrock-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: keyrock-two
    enabled: true
    source_path: applications/keyrock-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: keyrock-three
    enabled: true
    source_path: applications/keyrock-one
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: token-helper
    enabled: true
    source_path: applications/token-helper
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
