postgresql:
  fullnameOverride: postgresql
  auth:
    username: keycloak  
    enablePostgresUser: true
    existingSecret: postgres-secret
    secretKeys:
      adminPasswordKey: postgres-root-password
      userPasswordKey: postgres-password
  rbac:
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use    
  primary:
    initdb:
      scripts:
        create.sh: |
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE keycloak_one;"
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE keycloak_two;"
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE keycloak_three;"

