orion:
  deployment:
    additionalAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '8000'
  broker:
    db:
      hosts:
        - fiware-mongo-db-one-mongodb
      user: root
      existingSecret:
        name: mongodb-secret
        key: mongodb-root-password

  mongo:
    # we want to use the individually deployed mongodb
    enabled: false
