{{- if .Values.initScript.rolePolicy.policyEnabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: one-keyrock-policy-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
spec:
  containers:
    - name: policy-create
      image: quay.io/wi_stefan/mysql:5.7
      command: 
        - /bin/sh
        - /scripts/create.sh
      volumeMounts:
        - name: scripts
          mountPath: /scripts
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keyrock-secret
              key: dbPassword
  volumes:
    - name: scripts
      configMap:
        name: one-keyrock-create-policy-cm
  restartPolicy: Never
{{- end }}
