pdc-portal:
  deployment:
    image:
      repository: quay.io/i4trust/pdc-portal
      tag: 2.5.0
      pullPolicy: Always
    livenessProbe:
      initialDelaySeconds: 4
    readinessProbe:
      initialDelaySeconds: 5

  route:
    enabled: true
    host: portal-one.batterypass.fiware.dev
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    # should a certificate for the address automatically be generated
    certificate:
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-aws-prod

  debug:
    enabled: true

  config:
    title: "Batterypass Demo Portal"
    getLabel: "Get Battery"
    inputLabel: "Battery ID"
    client:
      id: "EU.EORI.NLPACKETDEL"

    external:
      host: https://portal-one.batterypass.fiware.dev

    oidc:
      redirect_path: "/openid_connect1.0/return"
      acr: "urn:http://eidas.europa.eu/LoA/NotNotified/high"

    cb:
      endpoint: "https://one.batterypass.fiware.dev/vc/ngsi-ld/v1"
      endpoint_siop: "https://one.batterypass.fiware.dev/vc/ngsi-ld/v1"
    
    express:
      port: 7000

        
    # Configuration for SIOP flow
    siop:
      # SIOP flow enabled
      enabled: true
      # Base uri of the verifier
      verifier_uri: https://verifier-one.batterypass.fiware.dev
      # DID of verifier
      did: "did:key:z6MkufEFkFSCXg1DHUsZbYuWcGf4QHat34YSoVgs67ED9m4S"

    idp:
