keyrock:
  statefulset:
    image:
      repository: quay.io/fiware/idm
      tag: i4trust-rc8
      pullPolicy: IfNotPresent

  db:
    user: root
    host: mysql-bp

  admin:
    user: admin
    email: admin@fiware.org

  existingSecret: keyrock-secret

  host: https://ar.batterypass.fiware.dev
  
  route:
    enabled: true
    host: ar.batterypass.fiware.dev
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    # should a certificate for the address automatically be generated
    certificate:
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-aws-prod

  ## Theme configuration for Keyrock
  theme:
    ## -- Enable theme
    enabled: false

  ## Configuration of Authorisation Registry (AR)
  authorisationRegistry:
    # -- Enable usage of authorisation registry
    enabled: true
    # -- Identifier (EORI) of AR
    identifier: "EU.EORI.DEBATTERYPASSAR"
    # -- URL of AR
    url: "internal"

  ## Configuration of iSHARE Satellite
  satellite:
    # -- Enable usage of satellite
    enabled: true
    # -- Identifier (EORI) of satellite
    identifier: "EU.EORI.DEBATTERYPASSSAT"
    # -- URL of satellite
    url: "https://satellite.batterypass.fiware.dev"
    # -- Token endpoint of satellite
    tokenEndpoint: "https://satellite.batterypass.fiware.dev/token"
    # -- Parties endpoint of satellite
    partiesEndpoint: "https://satellite.batterypass.fiware.dev/parties"

  ## -- Configuration of local key and certificate for validation and generation of tokens
  token:
    # -- Enable storage of local key and certificate
    enabled: true
    # -- Identifier (EORI) of local organisation
    identifier: "EU.EORI.DEBATTERYPASSAR"
    # BE AWARE: The following key and certificate configuration is highly unsecure, since its visible for everyone.
    # Use proper mechanisms to provide secrets, depending on your target environment. In a gitops-approach,
    # f.e. sealed-secrets could be a good solution: https://github.com/FIWARE-Ops/fiware-gitops#7-deploy-bitnamisealed-secrets
    # for training-purposes, we use the plain variant here, all certificates are self-signed and not used anywhere outside the demo-env
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIJKAIBAAKCAgEAreQlOgAVEYfoSGWmL4ZBr+39MLYrQzL7kNhLrhJDbwdmzf7S
      0SQVCZ80jVpzT+Z3wspKiONpl3cMMC+bMy0zJwvH/kF7+fDv1S4MOZr4MnKahMHz
      m7zyKQBktcEKzhPmHaS5zvOCgn288KjorTujGget86hmLnF8479VlJmkmLUr0t4L
      DbQMa4F9kK6KP8RYzMvU0NUG76RISkNlt4p+7Gacmoi8l/WyLnaNDrHpa2xmzBpR
      QBGqefwRxisAalnAz0VD3CuCQeXJMJLA0Opn9XtRsdAbQJsJYCexEN6aknwN/aNV
      LAwCYfnj3iAWlJ+1ilXuhCIFxbxjnDlkoW7w3HzQznpBBm/3XkC8UhmnvGaHTWl1
      E2gGPaz1eB12NF3vCnFvkhDUzfaUNapjFWI8iUvCiS7D8YCKDa9OkKCwRGadavSm
      R5MjGuFPPksrJpECEu0Jw5Hd8gmP+Qb3eEwYoh8dIMmRsdpaPpl4o0GCiyYH5kQR
      AjJ+uTcrvw4mLVNbm9kP79YTWqxh4n4olsCZ/b08Vcj3rf/QB+tyy5DBbOrf6Pt6
      AStkcfAnG5kjJpP5mW5XN/dQPesBH7GosHX6lD/7ShtW5WsHQe+bZIV9AmE9O9yZ
      XRwiLWgNkEZGE83/7RMneJaPGN7S1lkKa5bQYAo6XdBOiuH7N/T4C85167sCAwEA
      AQKCAgBU2yljZVjipiyu75OqS1zQqlVMqQjxkPZ8F2DPADCSBM2hJoHf9zig6mTt
      ub7dtbypfKfkpv0HIdv7w697yMnWewRMSc5jCLUwlXj3v2zwyUYoFLF5RTny0jNT
      EnHgYIuB2bmmiOQeI5fI5NQufRS5hhfX+Exsy4rDZMIxcsyEjJxnGV3RgRQyfg01
      RkdGmN0wiyM+CUaKOOPiAYOojlgjqmsvahyGFyqtS8LH8f/TISIE5a7Skgxb3Ksb
      xi48t7HEM6vKzByTZbvJDUQ0br7uZxBVshUqcL2hg5z/e3F4nDsDk+njRbT/9L7C
      zWvXeRxQ9mAfcK7acHU3bjZyJL46PAuNAwDhcTn9Wkpi5pvHSW9+ay7DwQAJG0yG
      7VVIU1+0uNQa3DaCHu2OmESndpci4TNNuL7u6uFkabyIyireC3B7eXjPmmwzrhTo
      CAQ1/ggXFlhyHH5/noRrujTYyboMzUUty1ktt757CPw6BaSYQvPxanN7iDzWiGar
      fZzNKLHTaHp59ezvIZ9peJKy5U8AUhXG1E9vz/krOjOafcQgexza/jMVBGO+3BFD
      6BGzVwr3oiV3aqeDZlIQDR2OeopLIp8t+6ItSU2LZZV1AaKfVTQqjXQvabHWOKN+
      v7jm7KnIivK6aoWwwWfttXWRRRiPbYr9GtC8r7EElE9yunPhkQKCAQEA4FQbIYCW
      86Loe89zLdIjI5LY5YdnBRub6Q9ZyF8YajBj1dH+Q7AP3Y+l5uEMGIJVd/ieJ655
      8RJaVX22bCmAy59troNaBR+hKrf+DjBZndXv5S1SyDoXFjhzZJ2XqfR2ACQli2Po
      85cITqPZ9tSHPDUELcYaMGp3QyhQXgV1waoeI3zWphZskoBMqywCK7ekjdY7jMrO
      Z3pPjVXzlELNxgE+rf7G7AP4sildOY0vFw/WSam5+FS1R9etCR1Vkjw6FjOYIud1
      UBXLwb/L8Jm+VtwuDoWQDD1JXEUNFI7Y22I0mjEM1Ulv7RTMVV8cGVeKubOq2m65
      bMbWaQ0T4cMPAwKCAQEAxnEV0RR7WQytQYV2v1ao/0bG9Xlv1x+K3nQe+VBo8dC5
      ivePrzHeIRbVDeLZEL6mOoEXaeOn+YMWyOwWnIbj9UwsJnF+doFTScT/R76ALq/k
      5PK20lxAeYZ1vV7bQfEEiv0mwKP5c2ukUFxCOHbIg4Nszmkl+7A5XLbFj7K92U/d
      QGbmj+r1fjdnSN8MD3pQRnGZFe84RsQ9feB7ePCG/eRW+xJjNk0l7BPaXQLslmfj
      Q/OTyLPwVQ5K9BB4JW6xBgEZtqq+6ow+cvKvXMT30hf9DdhmGRDIEtiAvCkmEyZW
      CD7YUkkNPjrzzljpaIA7xD1Sg0N1FF2QNi3AdeEW6QKCAQBw58Pz+71+CHtMfV/y
      KvaGnA1QkPK37mptRc2hfMNUBuDoqFV6Ce4iTH9qkdA9sbOEu3wWaslzHRKcPraG
      /+iUE7znfbLcK0w5rPtQduNT/m5MgaBNqHcgNu9VL8A6yRBvB8Jhwrpnh5elxPAa
      PGOIWQKuayuZPKyj/3FbsRHQlGew4s9CLr0ciziLWo4JJNfMj4vPU+/IwxWxBBah
      g3H/+3ZpqnbCKUmNmiYSpk2SJOVsk+FG7JOFAjdUBBCilm+B5xvmTWqNETtJW9gw
      U6EqJI2Fv5F9p4b5ysNHmpHo8Seah5925gxQXgxt133T/2ySBKy0XdAzwGv/2ZYt
      JbizAoIBAQCCoAYAbz8SyylxK+2S3fS4tVpaU+mu7fB3pnCNJMUwCHlaZMOMS4Mw
      vNraHS1NvHGnqTpEVbtIn2XsNJxdxN1hpxaY57SbRV4R/T8dduTh1p8RpkN6DYfT
      dxMh6MLjkUewRhuwSz/1HjI3Q8PDb01mZKjG5qg+GS5pPVam1L3rwoqdzh6PNdcL
      kmTGryw9NAKLnFNtAN9Glf70UUR1w77YeepXsy7jm70OvbLL7xTVnOUY4cmyH+Bf
      3Nyx8/Vijo6wqSDIAXVS56Zj/CQ7KN0Iywmkh4INleJdpW54bY3GpUGUg+nZoIS7
      Jgs/FX/vbhnpf4RFK65yDXTUdSFvdw+hAoIBAGonx/chxEBiU+AY2QXPgYNhx65w
      hl8WRqlg9y48ZuY8nDnPzABmrGibLqKwET2f3Id39J0oZ975PJOFQS42GvZnVQoo
      oi3V++OfeuSHHT86Q3kK34yKqGjI8VEgKJTVYTEa1dnDoG8tUmkgIwHB1tWSvkoT
      GfeM86YRPs9PqMZI2V6+9zUBA9FM3K5lFI7mKQXtqdgHdNgrWzkH9qyRX3Qc1MTj
      4c+5CMkmUiPKMl/kQ3UVSNmNMdSllD1hDUpt6jHADDzf7I7/jmFK+zZlidLGZ/fW
      5Ga0Ko5+1zW4mzO/YxAWNLHc6PReRaCVfy3ayz6sfen60HBEQQ71UJpsnI4=
      -----END RSA PRIVATE KEY-----

    cert: |
      -----BEGIN CERTIFICATE-----
      MIIGfTCCBGWgAwIBAgIUIZIDEQS68Mq8CT0HjlJwWIHCtWUwDQYJKoZIhvcNAQEL
      BQAwejELMAkGA1UEBhMCREUxDzANBgNVBAgMBkJlcmxpbjEfMB0GA1UECgwWRklX
      QVJFIEZvdW5kYXRpb24gZS5WLjEUMBIGA1UECwwLQmF0dGVyeXBhc3MxIzAhBgNV
      BAMMGkVVLkVPUkkuREVCQVRURVJZUEFTU0lOVEVSMB4XDTIzMDEyNjA2NTYyN1oX
      DTI4MDEyNTA2NTYyN1owga4xCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZCZXJsaW4x
      DzANBgNVBAcMBkJlcmxpbjEXMBUGA1UECgwOQmF0dGVyeXBhc3MgQVIxIDAeBgNV
      BAMMF0VVLkVPUkkuREVCQVRURVJZUEFTU0FSMSAwHgYJKoZIhvcNAQkBFhFjbGll
      bnRAZml3YXJlLm9yZzEgMB4GA1UEBRMXRVUuRU9SSS5ERUJBVFRFUllQQVNTQVIw
      ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCt5CU6ABURh+hIZaYvhkGv
      7f0wtitDMvuQ2EuuEkNvB2bN/tLRJBUJnzSNWnNP5nfCykqI42mXdwwwL5szLTMn
      C8f+QXv58O/VLgw5mvgycpqEwfObvPIpAGS1wQrOE+YdpLnO84KCfbzwqOitO6Ma
      B63zqGYucXzjv1WUmaSYtSvS3gsNtAxrgX2Qroo/xFjMy9TQ1QbvpEhKQ2W3in7s
      ZpyaiLyX9bIudo0OselrbGbMGlFAEap5/BHGKwBqWcDPRUPcK4JB5ckwksDQ6mf1
      e1Gx0BtAmwlgJ7EQ3pqSfA39o1UsDAJh+ePeIBaUn7WKVe6EIgXFvGOcOWShbvDc
      fNDOekEGb/deQLxSGae8ZodNaXUTaAY9rPV4HXY0Xe8KcW+SENTN9pQ1qmMVYjyJ
      S8KJLsPxgIoNr06QoLBEZp1q9KZHkyMa4U8+SysmkQIS7QnDkd3yCY/5Bvd4TBii
      Hx0gyZGx2lo+mXijQYKLJgfmRBECMn65Nyu/DiYtU1ub2Q/v1hNarGHifiiWwJn9
      vTxVyPet/9AH63LLkMFs6t/o+3oBK2Rx8CcbmSMmk/mZblc391A96wEfsaiwdfqU
      P/tKG1blawdB75tkhX0CYT073JldHCItaA2QRkYTzf/tEyd4lo8Y3tLWWQprltBg
      Cjpd0E6K4fs39PgLznXruwIDAQABo4HFMIHCMAkGA1UdEwQCMAAwEQYJYIZIAYb4
      QgEBBAQDAgWgMDMGCWCGSAGG+EIBDQQmFiRPcGVuU1NMIEdlbmVyYXRlZCBDbGll
      bnQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFP6UThiccuU12zS9W7vIMue5b4uOMB8G
      A1UdIwQYMBaAFDkgDX34GUC2o40JcYgBvQefOFztMA4GA1UdDwEB/wQEAwIF4DAd
      BgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwDQYJKoZIhvcNAQELBQADggIB
      ABjUsdznZ8kxP8b+AuJsxEu4C7u1NDYQKD7T1r9LwbRMRl+LWxOxVHpTAScpNcgM
      q5qthM1HNg1Qd3Bb/clpo73eIEARPytyR/SRJmRQTxk4n52zcRMgIjh7glAp2GGO
      gubP+qHxZmcOOeGe9LRazZYtGJ0or25BkZZQl9EEHUMXdxDkft75GeHqgacSq0ot
      huOHaAypUplY4BeWvejZCAK/6OvKNwex1Ly1homGM7lXIIZdcS3RX4aRXYoHYt4u
      Pt/F88a1Xcyn6rDAC7e3tkdv8HXv0RHWDk8eaaZPHlZ3ve07Pw885T1ptcQ5+2cL
      q4uwq8F1nbVbf2i/eiPJZ1NXf8yx4g06jlmfnLU7HTKe+Odh0qu0QQlaBIMUWIWR
      Zl/vYg0Gq1RTGtJ8oBx4B1C1STYLKr7vJG0hcmDhifzSqpgCa6KNlJ16mrMgyDEV
      aYgyS+6RI3RSqCPUjdwnZvCAmmIDbiXRqHdQLrBgBYOLP+rs/MhfAiTaHg/S3eGY
      llNFnWgK8TJwq8TwWYKba7V5vo7HjXcIMx7uuFc6NuNOm6t/M4WaoLkxC9j4U0PW
      L1MihUJhomQtCGNNi2W5Jj+3j5SUibDiKvuKvueIm4j9NUGP7GTHvhJwIu9OwYok
      EhWIMfvHowklz9unOsJ4V2vJSuHj4nnzkdQbnjxRjlOM
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIF5DCCA8ygAwIBAgIBAjANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCREUx
      DzANBgNVBAgMBkJlcmxpbjEPMA0GA1UEBwwGQmVybGluMR8wHQYDVQQKDBZGSVdB
      UkUgRm91bmRhdGlvbiBlLlYuMRQwEgYDVQQLDAtCYXR0ZXJ5cGFzczEgMB4GA1UE
      AwwXRVUuRU9SSS5ERUJBVFRFUllQQVNTQ0EwHhcNMjMwMTI2MDY0OTQ3WhcNMzAw
      NDI5MDY0OTQ3WjB6MQswCQYDVQQGEwJERTEPMA0GA1UECAwGQmVybGluMR8wHQYD
      VQQKDBZGSVdBUkUgRm91bmRhdGlvbiBlLlYuMRQwEgYDVQQLDAtCYXR0ZXJ5cGFz
      czEjMCEGA1UEAwwaRVUuRU9SSS5ERUJBVFRFUllQQVNTSU5URVIwggIiMA0GCSqG
      SIb3DQEBAQUAA4ICDwAwggIKAoICAQDYzJJkFxTBXygZiKlk0CurHYVxF2pUzvql
      IqbRoxPvdbpaHRw0Fx06lZQrZP/dAdlBkDEmn8fsrjK9vuAPXG6JdG5KsLcP5fL4
      BP53UqY7JKpsKvk83qkriahz7cyHzlE4yoynlqy/bfLMGtVrRysn+xOLnKflYrkJ
      /qrZBXUeeaRYLoiQZCVkA+nFWmDJveXoFeVwtetcGtb4boWxrGHxG6IQx9/IXSIV
      3uGRYxW3GMIgwB28x7BDdCO0+AcgFlKm2mehZ3FQwfC8exA4Qh1NHDYIUz1IlpvA
      Yd/S6ISj+zLRxk0eG3DBAYgug+64ayQn7KwzIb2NwDSVJLuC/uG1tglSdxrO2Msv
      ybww8+XWwgNM1fiO+BPnndP69HG+kTJbXvVyWzSiVjebM9GjruTy/MGi6FySFwU1
      lXiynoT72bpdOllL3oJe0SY2Auy41ETpJPGg+O/Q/9DzphMo16eSjBH047UgRlTp
      s6tcd+iydxxA1D6DxNdfkCApiX8aPxkxebg3/y3iZTGze5sGyMcBmjgddtDgpzX+
      d28RP3y8qOssb4WMGoG7jkBXPFnmzz7JYtEk7KhrKeM59IIHhfkP4b5kf5zrJfVi
      ID+p22iQhVSGkXU8FwQESjVOSTDEN3xv6Q/UK/3yGKBf2E/NVXAdJfST/KMD7KRk
      1icThoON2wIDAQABo2YwZDAdBgNVHQ4EFgQUOSANffgZQLajjQlxiAG9B584XO0w
      HwYDVR0jBBgwFoAUCyTQpHc4RA+Jyy9RN9pKGikUHcAwEgYDVR0TAQH/BAgwBgEB
      /wIBADAOBgNVHQ8BAf8EBAMCAYYwDQYJKoZIhvcNAQELBQADggIBAALHcn0NC1w9
      M4W+fcBdMh70WMJ/e+LdkeELrMKqNdQuIBb6kl+k7701CP4eq3qyPYul1U3H5xvD
      UMkRX0wh7GwfA1Lhc3UsMXxGLExh41yWvEG8GPAaIxMkiKdyckIUiZUm8NeGt/94
      RuaDOXMBLICN6q9Xhfz2YgQ0WtOQMwypnLvqGTPmdPky2ctGKvQciqxXy74N4/hb
      YinG8X88NZ2Tk82bLO/X2YZQat/A3U5Nnnwo0vjwJp/M0Tpr1J4n+GxKQG9rqfyP
      Ra9ByEnwogIYB7z47hkxeY8d2I12s6TmfLvX+PpKuwGhU0Xd6RCZet77texsKbQg
      yIOSrlPykc6eM6RAZa+cSA8kJA8cPfQN02sVZGpIgN3U575UOnOTEDLL9tFUQVNu
      ts0WwhVoyrmDdL6BZihmodLfTNRDrVow22bJGFNGUKqxB21pLcjSqkFKCFINoF5b
      CqVfe3EbCS1Q6PrPs7ApApNKHMxhp/FSpRscECB9qyy2mQ8CrL2YeqV+BmWxOqSA
      QCofUJnqRrjN+2+pzTd1qZtiwqnSl3KOnK7yOHz+++FZNu02SO2Z6kOjdwVK1+qs
      NvV2e7rMLMdlqtZ0a0Xl46uy6rQstbr4WvoFHgYpGRMDkjb51GCuhRC1WY+6osXq
      /rUbTNxHuAF3UdiLSC3mBpMzCeojr0az
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIF8zCCA9ugAwIBAgIUFk5tHQIDoLJ0yGMj5NmfvVTVrSAwDQYJKoZIhvcNAQEL
      BQAwgYgxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZCZXJsaW4xDzANBgNVBAcMBkJl
      cmxpbjEfMB0GA1UECgwWRklXQVJFIEZvdW5kYXRpb24gZS5WLjEUMBIGA1UECwwL
      QmF0dGVyeXBhc3MxIDAeBgNVBAMMF0VVLkVPUkkuREVCQVRURVJZUEFTU0NBMB4X
      DTIzMDEyNjA2NDgxOFoXDTMzMDEyMzA2NDgxOFowgYgxCzAJBgNVBAYTAkRFMQ8w
      DQYDVQQIDAZCZXJsaW4xDzANBgNVBAcMBkJlcmxpbjEfMB0GA1UECgwWRklXQVJF
      IEZvdW5kYXRpb24gZS5WLjEUMBIGA1UECwwLQmF0dGVyeXBhc3MxIDAeBgNVBAMM
      F0VVLkVPUkkuREVCQVRURVJZUEFTU0NBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
      MIICCgKCAgEAv3NVCmfddX9knGcQeEiIu9mT0RIIIrEx80hmYY+woWZbTfh2fwPW
      Y24vrcVAdy4M61Onvw/SGKk4LlWtlJXXDZ7P5ZeVsgTkF3DzbdhpfA4zwoWKt0L/
      Y/yxV5YIMvEsL33IkXRCSytUO5QSNgwP8zBAugqBYNGm3SBSLtPSvAeNficK3hLK
      ghk5ZKxnnN4OFNP3wCpDTGn09mtZ/xDMnC8nr7sCl27LdOHpfkVSdfcT5sBcI9A7
      wj/aCpDG8df+de3J7eHRXyurjV5B8XQ9ALdo4iZfSaPykG8IOnDo57VU/pd6/VB5
      TceCwzqUbWwwb2OhjRmJLR4rhrmyyfHN1HfuaivJyKBYhEF+zonV7aoh15CnKQM5
      fZ0AYmbT5jj7hHHSviGZUYMcFNvIJqiyJbwlvelmuypOYpQLmh9O8UQMMPGunXRJ
      9zv8e10xeOtcEka1aAzGfhoSt7GDYDtm5xwya2/0VYYaxM0vflsadf+Zf8N/j6Zd
      pCu7iUgRsFN06efNcm9UH4A72BQgZv7eBQip9fAtXfjJ45ZENupIn51zqUoNMoem
      OiqNCcL8cd4fpBaBd5KO4hYmxdCTEi8ETnPr8O8fV8ie0fDFM2qKdls9bToE19M9
      r/a9VHl0ePO8UEK7RzdUy7R2zoXOYtycAJZv2wGAIlLBKq0bx91QEYMCAwEAAaNT
      MFEwHQYDVR0OBBYEFAsk0KR3OEQPicsvUTfaShopFB3AMB8GA1UdIwQYMBaAFAsk
      0KR3OEQPicsvUTfaShopFB3AMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
      BQADggIBAHLO9BD9nu7XyJRqdCe8GJUR2sdAdEfQZ2VjLOk+kAHO/mfUH9cEj+db
      jlS3utMXhVaXNRIrEzNDPDqGst+9KDfZ7CIDzqKNeLw0KKYgX8TOI3S7GbHxqO/I
      qnFEzeGK6KmOxofzqa3vuPKUySv8MH7NavwFvy/EqUruo+cZTedvs9QAzneyK3pk
      wx8HKNFCNCTP48w0x8n2jz3ogqOrC6EcepxSlrRGWmoyBUu/CMTD8Q2T7QnoF2BQ
      lScfJ24whiPAMswJF7jBMBfdLNplbafzLQCudc6LG7iOfBX8lEx0WETd6pwMItaf
      Zqg3qm5nAjYFXjOuSOW2oFZ+01WKv3VIJMKHPGLoti3SX1COHEBkLNFz5PzeyfHK
      oeOVfPwH1wGeK37qvmbHAROCBmVkn6ebrnylxef/U+eT83Efe/LFBs2nuBXBMktc
      +qQAP5rTzC+yUIks48zeBiCliPqYeLPA2tn3DT02RJD47ufz+zaLrK1IAfDXzYBn
      nuJov/y4Gw/jjgCLOp8H+Q5PzxuCH5OY41INyo4l9+cfw1rm+2AiajbxYA8rrajt
      l5xZxU66ududjKTZ6KX6W2o4s0z2i7kjNFJdQEmR2kRzbXkcXPk/5dAbRVMJOQd4
      oTUhlBGrrdojMmk5+nftXaQ6l/RCitCLlD3MD7EKbRs1sLDXsUMG
      -----END CERTIFICATE-----

  additionalEnvVars:
    - name: IDM_TITLE
      value: "Batterypass Authorization Registry"
    - name: IDM_DEBUG
      value: "true"
    - name: DEBUG
      value: "*"
    - name: IDM_DB_NAME
      value: bp_ar_idm
    - name: IDM_DB_SEED
      value: "true"
    - name: IDM_SERVER_MAX_HEADER_SIZE
      value: "32768"
