apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-key
data:
  keyfile.json: |-
    {
      "kty": "OKP",
      "d": "EIS4wKdqmsbVNOzg9LNiaa7vjjJBHwzWkX-xxCHT_sg",
      "use": "sig",
      "crv": "Ed25519",
      "kid": "z6MkkSMQG86ZC5pcJUXNg1evKugKjstRbUhWmMKwt1hE3Pmq",
      "x": "WOqY5DLirr4NoinvrlN7aD9GwyNITQgY40MCdmh2C-A",
      "alg": "EdDSA"
    }