apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ishare-token-helper.fullname" . }}-certs
  labels:
    {{- include "ishare-token-helper.labels" . | nindent 4 }}
data:
  {{- with .Values.certs }}
  {{- toYaml . | nindent 2 }}
  {{- end }}