apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ishare-token-helper.fullname" . }}
  labels:
    {{- include "ishare-token-helper.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}