{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ishare-token-helper.serviceAccountName" . }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "ishare-token-helper.labels" . | nindent 4 }}
{{- end }}
